### ISSUE TITLE
snackbar.d.ts' is not a module

### ISSUE THREAD

**Issue by KiPSOFT** [MostafaMDZH/Typescript-Components#1]
Hi, I'm getting this error ? What's solution ?

Thanks.

**Comment by MostafaMDZH** [comment]
Hi,
More information please,
Are you using Typescript? what is your framework? how did you import the component?

**Comment by KiPSOFT** [comment]
Hi,

I'm using typescript. I don't use any framework. import usage; import Snackbar from 'awesome-snackbar';

**Comment by KiPSOFT** [comment]
Work around. I'm added declare module in my d.ts file.

**Comment by MostafaMDZH** [comment]
Just solved the problem, please update to version 2.0.2
Thanks for your feedback.

**Comment by MostafaMDZH** [comment]
Please check out the release notes:
https://github.com/MostafaMDZH/Awesome-Snackbar/releases/tag/V2.0.0
If everything is working fine please tell me to close this issue.
thanks
